package com.example.nepaltourism.classes.enums;

public enum NAVIGATIONS {
    LOGINPAGE,
    REGISTERPAGE,
    ADMINPAGE,
    TOURISTPAGE,
    GUIDEPAGE,
    MYBOOKINGPAGE,
    GUIDEMYBOOKINGPAGE,
    ATRRACTIONPAGE,
    GUIDEUSERPAGE,
    TOURISTUSERPAGE,
    FESTIVALPAGE,
    ALERTPAGE,
    GUIDEALERTPAGE,
    ALERTEDITPAGE,
    BOOKINGPAGE,
    TOURISTCONTROLPAGE,
    GUIDECONTROLPAGE,
    ATTRACTIONCONTROLPAGE,
    BOOKINGCONTROLPAGE,
    ADMINUSERPAGE,
    FESTIVALCONTROLPAGE, FESTIVALEDIT, ALERTEDIT;
}
